### ISSUE TITLE
AiMos Operational

### ISSUE THREAD

**Issue by gregjhansell97** [gregjhansell97/mpi-radio-transceiver#1]
The MPI design we are currently using requires concurrent MPI operations. "multi-threaded" MPI is not supported by default and must be requested. If AiMos for some reason doesn't support this then we must re-evaluate our design decisions. (Hopefully it does support it)

https://github.com/gregjhansell97/mpi-radio-transceiver/blob/99721c5eed8ab162d5cc9706fdd4294c4ae05fc9/mpi_tests.cpp#L22-L27

**Comment by chrisatang** [comment]
See script in Disc chat.
