### ISSUE TITLE
Change name of buffer to mpi_msg in mpi_listener

### ISSUE THREAD

**Issue by gregjhansell97** [gregjhansell97/mpi-radio-transceiver#3]
Currently the word buffer is used way too much and it is confusing. I would like the word buffer to reflect data that is buffered on the transceiver waiting to be flushed out by receive operations:

https://github.com/gregjhansell97/mpi-radio-transceiver/blob/99721c5eed8ab162d5cc9706fdd4294c4ae05fc9/mpi_radio_transceiver.cpp#L185-L207

The word buffer is also being used in the MPI calls to receive an mpi message. It would be a lot cleaner to call these "mpi_msg"

https://github.com/gregjhansell97/mpi-radio-transceiver/blob/99721c5eed8ab162d5cc9706fdd4294c4ae05fc9/mpi_radio_transceiver.cpp#L57-L81

**Comment by chrisatang** [comment]
Whoops, leaving this up for nits and critiques.
