### ISSUE TITLE
Change size of m_buffer for transceivers

### ISSUE THREAD

**Issue by gregjhansell97** [gregjhansell97/mpi-radio-transceiver#5]
The current m_buffer size reflects the max-buffer-size suggested 'B', but that is just the max-amount of bytes from MESSAGES. The m_buffer will also have header information about the size of the message, so the m_buffer needs to be larger than the desired max-buffer-size. How much larger? Well in the worst case you could have each message be size one, then you could have 'B' messages, that means the size which is sizeof(size_t) takes up 'B'*sizeof(size_t) to store each length, bring the total to 'B' + 'B'*sizeof(size_t) which should be size of each m_buffer

https://github.com/gregjhansell97/mpi-radio-transceiver/blob/99721c5eed8ab162d5cc9706fdd4294c4ae05fc9/mpi_radio_transceiver.h#L42-L57

**Comment by chrisatang** [comment]
We're no longer lumping on the actual size of the message at the head; instead the header is the struct mentioned in #6 , so it'd be B * sizeof(MPI_Message).

This is not the most clear-cut way to take the actual size of the struct ([see this StackOverflow explanation](https://stackoverflow.com/questions/119123/why-isnt-sizeof-for-a-struct-equal-to-the-sum-of-sizeof-of-each-member)); however, I don't see any big issues with this approach memory-wise.

Let me know your thoughts!
